### ISSUE TITLE
cobol outdated💀

### ISSUE THREAD

**Issue by Sonic1paRadise** [david-a-redick/imaze#1]
```
Xt_fenster.c:787:3: error: call to undeclared function 'handle_signal'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

**Comment by david-a-redick** [comment]
I've corrected this an created a branch 'better-c'.
Can you try it out and let me know if you have any other problems?

**Comment by Sonic1paRadise** [comment]
Worked, but with legacy ui, instead of motif as on most screenshots

**Comment by david-a-redick** [comment]
Thanks for the feedback.

My debian box is happy so there must be something different.

Can you run and send me the output for these commands:

uname -a

lsb_release -a

**Comment by Sonic1paRadise** [comment]
No lsb_release, but as for name, here’s the stats:
Darwin Mac-mini-dobkun.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64


> 13 черв. 2023 р. о 16:19 david-a-redick ***@***.***> написав(ла):
> 
> lsb_release -a

**Comment by david-a-redick** [comment]
Unfortunately, imaze was created before MacOS and pkg-config became available.

I added some rudimentary support in the configure script.

https://github.com/david-a-redick/imaze/blob/better-c/source/configure#L119

I don't have access to a MacOS machine so I'm coding blindly.

Rerun configure and let me know how that turns out.
